#!/bin/sh

TOPDIR=`cd .. && pwd`

JMDNSDIR=/Users/dglo/Desktop/jmdns-1.0

CLASSPATH=$TOPDIR/build/autoconf/classes:$JMDNSDIR/lib/jmdns.jar
export CLASSPATH

exec java -Xmx2048m icecube.daq.config.AutoConfig $@
