#!/bin/sh

if [ $# -lt 1 ]; then
    echo "$0: Please specify test class to run" >&2
    exit 1
fi
app=$1
shift

TOPDIR=`cd .. && pwd`

CLASSPATH=$TOPDIR/lib/juggler.jar:$TOPDIR/lib/juggler-test.jar:$TOPDIR/tools/lib/commons-logging.jar:$TOPDIR/tools/lib/jmxtools.jar:$TOPDIR/tools/lib/junit.jar
export CLASSPATH

java \
    -Dcom.sun.management.jmxremote \
    icecube.daq.juggler.mbean.test.$app \
    $@
