
package icecube.daq.juggler.component;

public class StateTransition
{
    static final StateTransition LIST[] = new StateTransition[] {
        new StateTransition(DAQState.IDLE, StateAction.DO_CONFIGURE,
                            "Cannot configure component comp from state idle",
                            DAQState.IDLE, DAQState.IDLE,
                            CompFunc.NONE),
        new StateTransition(DAQState.IDLE, StateAction.DO_CONNECT,
                            null,
                            DAQState.CONNECTING, DAQState.CONNECTED,
                            CompFunc.NONE),
        new StateTransition(DAQState.IDLE, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.IDLE, StateAction.DO_DISCONNECT,
                            null,
                            DAQState.IDLE, DAQState.IDLE,
                            CompFunc.NONE),
        new StateTransition(DAQState.IDLE, StateAction.DO_FORCED_STOP,
                            "Cannot force-stop component comp from state idle",
                            DAQState.IDLE, DAQState.IDLE,
                            CompFunc.NONE),
        new StateTransition(DAQState.IDLE, StateAction.DO_RESET,
                            null,
                            DAQState.IDLE, DAQState.IDLE,
                            CompFunc.NONE),
        new StateTransition(DAQState.IDLE, StateAction.DO_START_RUN,
                            "Cannot start component comp from state idle",
                            DAQState.IDLE, DAQState.IDLE,
                            CompFunc.NONE),
        new StateTransition(DAQState.IDLE, StateAction.DO_STOP_RUN,
                            "Cannot stop component comp from state idle",
                            DAQState.IDLE, DAQState.IDLE,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONNECTING, StateAction.DO_CONFIGURE,
                            "Cannot configure component comp from state connecting",
                            DAQState.CONNECTING, DAQState.CONNECTED,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONNECTING, StateAction.DO_CONNECT,
                            "Cannot connect component comp from state connecting (should be idle)",
                            DAQState.CONNECTING, DAQState.CONNECTED,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONNECTING, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.CONNECTING, StateAction.DO_DISCONNECT,
                            null,
                            DAQState.DISCONNECTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES),
        new StateTransition(DAQState.CONNECTING, StateAction.DO_FORCED_STOP,
                            "Cannot force-stop component comp from state connecting",
                            DAQState.CONNECTING, DAQState.CONNECTED,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONNECTING, StateAction.DO_RESET,
                            null,
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES|CompFunc.RESETTING),
        new StateTransition(DAQState.CONNECTING, StateAction.DO_START_RUN,
                            "Cannot start component comp from state connecting",
                            DAQState.CONNECTING, DAQState.CONNECTED,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONNECTING, StateAction.DO_STOP_RUN,
                            "Cannot stop component comp from state connecting",
                            DAQState.CONNECTING, DAQState.CONNECTED,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONNECTED, StateAction.DO_CONFIGURE,
                            null,
                            DAQState.CONFIGURING, DAQState.READY,
                            CompFunc.CONFIGURING),
        new StateTransition(DAQState.CONNECTED, StateAction.DO_CONNECT,
                            "Cannot connect component comp from state connected (should be idle)",
                            DAQState.CONNECTED, DAQState.CONNECTED,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONNECTED, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.CONNECTED, StateAction.DO_DISCONNECT,
                            null,
                            DAQState.DISCONNECTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES),
        new StateTransition(DAQState.CONNECTED, StateAction.DO_FORCED_STOP,
                            "Cannot force-stop component comp from state connected",
                            DAQState.CONNECTED, DAQState.CONNECTED,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONNECTED, StateAction.DO_RESET,
                            null,
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES|CompFunc.RESETTING),
        new StateTransition(DAQState.CONNECTED, StateAction.DO_START_RUN,
                            "Cannot start component comp from state connected",
                            DAQState.CONNECTED, DAQState.CONNECTED,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONNECTED, StateAction.DO_STOP_RUN,
                            "Cannot stop component comp from state connected",
                            DAQState.CONNECTED, DAQState.CONNECTED,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONFIGURING, StateAction.DO_CONFIGURE,
                            null,
                            DAQState.CONFIGURING, DAQState.READY,
                            CompFunc.CONFIGURING),
        new StateTransition(DAQState.CONFIGURING, StateAction.DO_CONNECT,
                            "Cannot connect component comp from state configuring (should be idle)",
                            DAQState.CONFIGURING, DAQState.READY,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONFIGURING, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.CONFIGURING, StateAction.DO_DISCONNECT,
                            null,
                            DAQState.DISCONNECTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES),
        new StateTransition(DAQState.CONFIGURING, StateAction.DO_FORCED_STOP,
                            "Cannot force-stop component comp from state configuring",
                            DAQState.CONFIGURING, DAQState.READY,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONFIGURING, StateAction.DO_RESET,
                            null,
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES|CompFunc.RESETTING),
        new StateTransition(DAQState.CONFIGURING, StateAction.DO_START_RUN,
                            "Cannot start component comp from state configuring",
                            DAQState.CONFIGURING, DAQState.READY,
                            CompFunc.NONE),
        new StateTransition(DAQState.CONFIGURING, StateAction.DO_STOP_RUN,
                            "Cannot stop component comp from state configuring",
                            DAQState.CONFIGURING, DAQState.READY,
                            CompFunc.NONE),
        new StateTransition(DAQState.READY, StateAction.DO_CONFIGURE,
                            null,
                            DAQState.CONFIGURING, DAQState.READY,
                            CompFunc.CONFIGURING),
        new StateTransition(DAQState.READY, StateAction.DO_CONNECT,
                            "Cannot connect component comp from state ready (should be idle)",
                            DAQState.READY, DAQState.READY,
                            CompFunc.NONE),
        new StateTransition(DAQState.READY, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.READY, StateAction.DO_DISCONNECT,
                            null,
                            DAQState.DISCONNECTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES),
        new StateTransition(DAQState.READY, StateAction.DO_FORCED_STOP,
                            null,
                            DAQState.READY, DAQState.READY,
                            CompFunc.NONE),
        new StateTransition(DAQState.READY, StateAction.DO_RESET,
                            null,
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES|CompFunc.RESETTING),
        new StateTransition(DAQState.READY, StateAction.DO_START_RUN,
                            null,
                            DAQState.STARTING, DAQState.RUNNING,
                            CompFunc.SET_RUN_NUMBER|CompFunc.START_ENGINES|CompFunc.STARTING|CompFunc.STARTED),
        new StateTransition(DAQState.READY, StateAction.DO_STOP_RUN,
                            null,
                            DAQState.READY, DAQState.READY,
                            CompFunc.NONE),
        new StateTransition(DAQState.STARTING, StateAction.DO_CONFIGURE,
                            "Cannot configure component comp from state starting",
                            DAQState.STARTING, DAQState.RUNNING,
                            CompFunc.SET_RUN_NUMBER|CompFunc.START_ENGINES|CompFunc.STARTING|CompFunc.STARTED),
        new StateTransition(DAQState.STARTING, StateAction.DO_CONNECT,
                            "Cannot connect component comp from state starting (should be idle)",
                            DAQState.STARTING, DAQState.RUNNING,
                            CompFunc.SET_RUN_NUMBER|CompFunc.START_ENGINES|CompFunc.STARTING|CompFunc.STARTED),
        new StateTransition(DAQState.STARTING, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.STARTING, StateAction.DO_DISCONNECT,
                            "Cannot disconnect component comp from state starting",
                            DAQState.STARTING, DAQState.RUNNING,
                            CompFunc.SET_RUN_NUMBER|CompFunc.START_ENGINES|CompFunc.STARTING|CompFunc.STARTED),
        new StateTransition(DAQState.STARTING, StateAction.DO_FORCED_STOP,
                            "Cannot force-stop component comp from state starting",
                            DAQState.STARTING, DAQState.RUNNING,
                            CompFunc.SET_RUN_NUMBER|CompFunc.START_ENGINES|CompFunc.STARTING|CompFunc.STARTED),
        new StateTransition(DAQState.STARTING, StateAction.DO_RESET,
                            null,
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.STOPPED|CompFunc.STOPPING|CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES|CompFunc.RESETTING),
        new StateTransition(DAQState.STARTING, StateAction.DO_START_RUN,
                            null,
                            DAQState.STARTING, DAQState.RUNNING,
                            CompFunc.SET_RUN_NUMBER|CompFunc.START_ENGINES|CompFunc.STARTING|CompFunc.STARTED),
        new StateTransition(DAQState.STARTING, StateAction.DO_STOP_RUN,
                            "Cannot stop component comp from state starting",
                            DAQState.STARTING, DAQState.RUNNING,
                            CompFunc.SET_RUN_NUMBER|CompFunc.START_ENGINES|CompFunc.STARTING|CompFunc.STARTED),
        new StateTransition(DAQState.RUNNING, StateAction.DO_CONFIGURE,
                            "Cannot configure component comp from state running",
                            DAQState.RUNNING, DAQState.RUNNING,
                            CompFunc.NONE),
        new StateTransition(DAQState.RUNNING, StateAction.DO_CONNECT,
                            "Cannot connect component comp from state running (should be idle)",
                            DAQState.RUNNING, DAQState.RUNNING,
                            CompFunc.NONE),
        new StateTransition(DAQState.RUNNING, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.RUNNING, StateAction.DO_DISCONNECT,
                            "Cannot disconnect component comp from state running",
                            DAQState.RUNNING, DAQState.RUNNING,
                            CompFunc.NONE),
        new StateTransition(DAQState.RUNNING, StateAction.DO_FORCED_STOP,
                            null,
                            DAQState.FORCING_STOP, DAQState.READY,
                            CompFunc.STOPPED),
        new StateTransition(DAQState.RUNNING, StateAction.DO_RESET,
                            null,
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.STOPPED|CompFunc.STOPPING|CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES|CompFunc.RESETTING),
        new StateTransition(DAQState.RUNNING, StateAction.DO_START_RUN,
                            null,
                            DAQState.RUNNING, DAQState.RUNNING,
                            CompFunc.NONE),
        new StateTransition(DAQState.RUNNING, StateAction.DO_STOP_RUN,
                            null,
                            DAQState.STOPPING, DAQState.READY,
                            CompFunc.STOPPING|CompFunc.STOPPED),
        new StateTransition(DAQState.STOPPING, StateAction.DO_CONFIGURE,
                            "Cannot configure component comp from state stopping",
                            DAQState.STOPPING, DAQState.READY,
                            CompFunc.STOPPING|CompFunc.STOPPED),
        new StateTransition(DAQState.STOPPING, StateAction.DO_CONNECT,
                            "Cannot connect component comp from state stopping (should be idle)",
                            DAQState.STOPPING, DAQState.READY,
                            CompFunc.STOPPING|CompFunc.STOPPED),
        new StateTransition(DAQState.STOPPING, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.STOPPING, StateAction.DO_DISCONNECT,
                            "Cannot disconnect component comp from state stopping",
                            DAQState.STOPPING, DAQState.READY,
                            CompFunc.STOPPING|CompFunc.STOPPED),
        new StateTransition(DAQState.STOPPING, StateAction.DO_FORCED_STOP,
                            null,
                            DAQState.FORCING_STOP, DAQState.READY,
                            CompFunc.STOPPED),
        new StateTransition(DAQState.STOPPING, StateAction.DO_RESET,
                            null,
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.STOPPED|CompFunc.STOPPING|CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES|CompFunc.RESETTING),
        new StateTransition(DAQState.STOPPING, StateAction.DO_START_RUN,
                            "Cannot start component comp from state stopping",
                            DAQState.STOPPING, DAQState.READY,
                            CompFunc.STOPPING|CompFunc.STOPPED),
        new StateTransition(DAQState.STOPPING, StateAction.DO_STOP_RUN,
                            null,
                            DAQState.STOPPING, DAQState.READY,
                            CompFunc.STOPPING|CompFunc.STOPPED|CompFunc.STOPPING|CompFunc.STOPPED),
        new StateTransition(DAQState.DISCONNECTING, StateAction.DO_CONFIGURE,
                            "Cannot configure component comp from state disconnecting",
                            DAQState.DISCONNECTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES),
        new StateTransition(DAQState.DISCONNECTING, StateAction.DO_CONNECT,
                            "Cannot connect component comp from state disconnecting (should be idle)",
                            DAQState.DISCONNECTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES),
        new StateTransition(DAQState.DISCONNECTING, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.DISCONNECTING, StateAction.DO_DISCONNECT,
                            null,
                            DAQState.DISCONNECTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES|CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES),
        new StateTransition(DAQState.DISCONNECTING, StateAction.DO_FORCED_STOP,
                            "Cannot force-stop component comp from state disconnecting",
                            DAQState.DISCONNECTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES),
        new StateTransition(DAQState.DISCONNECTING, StateAction.DO_RESET,
                            null,
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES|CompFunc.RESETTING),
        new StateTransition(DAQState.DISCONNECTING, StateAction.DO_START_RUN,
                            "Cannot start component comp from state disconnecting",
                            DAQState.DISCONNECTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES),
        new StateTransition(DAQState.DISCONNECTING, StateAction.DO_STOP_RUN,
                            "Cannot stop component comp from state disconnecting",
                            DAQState.DISCONNECTING, DAQState.IDLE,
                            CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES),
        new StateTransition(DAQState.DESTROYED, StateAction.DO_CONFIGURE,
                            "Cannot configure component comp from state destroyed",
                            DAQState.DESTROYED, DAQState.DESTROYED,
                            CompFunc.NONE),
        new StateTransition(DAQState.DESTROYED, StateAction.DO_CONNECT,
                            "Cannot connect component comp from state destroyed (should be idle)",
                            DAQState.DESTROYED, DAQState.DESTROYED,
                            CompFunc.NONE),
        new StateTransition(DAQState.DESTROYED, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYED, DAQState.DESTROYED,
                            CompFunc.NONE),
        new StateTransition(DAQState.DESTROYED, StateAction.DO_DISCONNECT,
                            "Cannot disconnect component comp from state destroyed",
                            DAQState.DESTROYED, DAQState.DESTROYED,
                            CompFunc.NONE),
        new StateTransition(DAQState.DESTROYED, StateAction.DO_FORCED_STOP,
                            "Cannot force-stop component comp from state destroyed",
                            DAQState.DESTROYED, DAQState.DESTROYED,
                            CompFunc.NONE),
        new StateTransition(DAQState.DESTROYED, StateAction.DO_RESET,
                            null,
                            DAQState.DESTROYED, DAQState.DESTROYED,
                            CompFunc.NONE),
        new StateTransition(DAQState.DESTROYED, StateAction.DO_START_RUN,
                            "Cannot start component comp from state destroyed",
                            DAQState.DESTROYED, DAQState.DESTROYED,
                            CompFunc.NONE),
        new StateTransition(DAQState.DESTROYED, StateAction.DO_STOP_RUN,
                            "Cannot stop component comp from state destroyed",
                            DAQState.DESTROYED, DAQState.DESTROYED,
                            CompFunc.NONE),
        new StateTransition(DAQState.FORCING_STOP, StateAction.DO_CONFIGURE,
                            "Cannot configure component comp from state forcingStop",
                            DAQState.FORCING_STOP, DAQState.READY,
                            CompFunc.STOPPED),
        new StateTransition(DAQState.FORCING_STOP, StateAction.DO_CONNECT,
                            "Cannot connect component comp from state forcingStop (should be idle)",
                            DAQState.FORCING_STOP, DAQState.READY,
                            CompFunc.STOPPED),
        new StateTransition(DAQState.FORCING_STOP, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.FORCING_STOP, StateAction.DO_DISCONNECT,
                            "Cannot disconnect component comp from state forcingStop",
                            DAQState.FORCING_STOP, DAQState.READY,
                            CompFunc.STOPPED),
        new StateTransition(DAQState.FORCING_STOP, StateAction.DO_FORCED_STOP,
                            null,
                            DAQState.FORCING_STOP, DAQState.READY,
                            CompFunc.STOPPED),
        new StateTransition(DAQState.FORCING_STOP, StateAction.DO_RESET,
                            null,
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.STOPPED|CompFunc.STOPPING|CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES|CompFunc.RESETTING),
        new StateTransition(DAQState.FORCING_STOP, StateAction.DO_START_RUN,
                            "Cannot start component comp from state forcingStop",
                            DAQState.FORCING_STOP, DAQState.READY,
                            CompFunc.STOPPED),
        new StateTransition(DAQState.FORCING_STOP, StateAction.DO_STOP_RUN,
                            "Cannot stop component comp from state forcingStop",
                            DAQState.FORCING_STOP, DAQState.READY,
                            CompFunc.STOPPED),
        new StateTransition(DAQState.DESTROYING, StateAction.DO_CONFIGURE,
                            "Cannot configure component comp from state destroying",
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.DESTROYING, StateAction.DO_CONNECT,
                            "Cannot connect component comp from state destroying (should be idle)",
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.DESTROYING, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK|CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.DESTROYING, StateAction.DO_DISCONNECT,
                            "Cannot disconnect component comp from state destroying",
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.DESTROYING, StateAction.DO_FORCED_STOP,
                            "Cannot force-stop component comp from state destroying",
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.DESTROYING, StateAction.DO_RESET,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.DESTROYING, StateAction.DO_START_RUN,
                            "Cannot start component comp from state destroying",
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.DESTROYING, StateAction.DO_STOP_RUN,
                            "Cannot stop component comp from state destroying",
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.RESETTING, StateAction.DO_CONFIGURE,
                            "Cannot configure component comp from state resetting",
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.RESETTING),
        new StateTransition(DAQState.RESETTING, StateAction.DO_CONNECT,
                            "Cannot connect component comp from state resetting (should be idle)",
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.RESETTING),
        new StateTransition(DAQState.RESETTING, StateAction.DO_DESTROY,
                            null,
                            DAQState.DESTROYING, DAQState.DESTROYED,
                            CompFunc.STOP_MBEAN_AGENT|CompFunc.STOP_STATE_TASK),
        new StateTransition(DAQState.RESETTING, StateAction.DO_DISCONNECT,
                            "Cannot disconnect component comp from state resetting",
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.RESETTING),
        new StateTransition(DAQState.RESETTING, StateAction.DO_FORCED_STOP,
                            "Cannot force-stop component comp from state resetting",
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.RESETTING),
        new StateTransition(DAQState.RESETTING, StateAction.DO_RESET,
                            null,
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.STOPPING|CompFunc.STOPPED|CompFunc.DISCONNECTED|CompFunc.FLUSH_CACHES|CompFunc.RESETTING|CompFunc.RESETTING),
        new StateTransition(DAQState.RESETTING, StateAction.DO_START_RUN,
                            "Cannot start component comp from state resetting",
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.RESETTING),
        new StateTransition(DAQState.RESETTING, StateAction.DO_STOP_RUN,
                            "Cannot stop component comp from state resetting",
                            DAQState.RESETTING, DAQState.IDLE,
                            CompFunc.RESETTING),

    };

    private DAQState oldState;
    private StateAction action;
    private String exceptionMsg;
    private DAQState midState;
    private DAQState endState;
    private int funcBitmap;

    StateTransition(DAQState oldState, StateAction action, String exceptionMsg,
                    DAQState midState, DAQState endState, int funcBitmap)
    {
        this.oldState = oldState;
        this.action = action;
        this.exceptionMsg = exceptionMsg;
        this.midState = midState;
        this.endState = endState;
        this.funcBitmap = funcBitmap;
    }

    StateAction getAction() { return action; }
    DAQState getEndState() { return endState; }
    int getFunctionBitmap() { return funcBitmap; }
    String getExceptionMessage() { return exceptionMsg; }
    DAQState getMidState() { return midState; }
    DAQState getOldState() { return oldState; }
}
